version: '2'
services:
  mysql:
    image: mysql
    container_name: test-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
   
  web:
    build: .
    container_name: test-app
    working_dir: /usr/src/app
    
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: root